import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Aside } from "@/components/Aside";
import { getPathname } from "@/helpers/getPathname";

const geistSans = Inter({
    variable: "--font-inter",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    preload: true,
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    const pathname = await getPathname();

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} antialiased grid grid-cols-[minmax(200px,_260px)_1fr]`}
            >
                <Aside />
                <main className="w-full">
                    <Header pathname={pathname} />
                    {children}
                </main>
            </body>
        </html>
    );
};

export default RootLayout;
